name = "Tango"
uuid = "79a4dc96-51c1-419e-be81-607bf600acbd"
authors = ["Obanmarcos <obandomarcos96@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
